#!/usr/bin/env node

var control = require( "src-ctrl" );

control.hooks["pre-commit"]()
	.then( function( result ) {
		process.exit( 0 );
	}, function( err ) {
		process.exit( err.code || 1 );
	} );
